# Generated by Django 4.2 on 2025-12-20 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok', models.PositiveIntegerField()),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='paket_images/')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Paket',
                'verbose_name_plural': 'Paket',
            },
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('nomor_telepon', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pelanggan',
                'verbose_name_plural': 'Pelanggan',
            },
        ),
        migrations.CreateModel(
            name='Penyewaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_pasang', models.DateTimeField()),
                ('tgl_kembali', models.DateTimeField()),
                ('ongkir', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paket')),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pelanggan')),
            ],
            options={
                'verbose_name': 'Penyewaan',
                'verbose_name_plural': 'Penyewaan',
            },
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_bayar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metode_pembayaran', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('tanggal_transaksi', models.DateTimeField(auto_now_add=True)),
                ('referensi_pembayaran', models.CharField(blank=True, max_length=100, null=True)),
                ('penyewaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.penyewaan')),
            ],
            options={
                'verbose_name': 'Transaksi',
                'verbose_name_plural': 'Transaksi',
            },
        ),
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger'), ('success', 'Success')], default='info', max_length=20)),
                ('judul', models.CharField(max_length=100)),
                ('pesan', models.TextField()),
                ('sudah_dibaca', models.BooleanField(default=False)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notifikasi',
                'verbose_name_plural': 'Notifikasi',
                'ordering': ['-tanggal_dibuat'],
            },
        ),
        migrations.CreateModel(
            name='DetailPenyewaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField()),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('penyewaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.penyewaan')),
            ],
            options={
                'verbose_name': 'Detail Penyewaan',
                'verbose_name_plural': 'Detail Penyewaan',
            },
        ),
    ]
