# Generated by Django 4.2 on 2025-12-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penyewaan',
            name='ongkir',
        ),
        migrations.AddField(
            model_name='penyewaan',
            name='ongkos_kirim',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='detailpenyewaan',
            name='harga_satuan',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='notifikasi',
            name='jenis',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Peringatan'), ('danger', 'Bahaya'), ('success', 'Sukses')], default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='paket',
            name='harga',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='penyewaan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Dikonfirmasi'), ('cancelled', 'Dibatalkan'), ('completed', 'Selesai')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='jumlah_bayar',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Dibayar'), ('failed', 'Gagal')], default='pending', max_length=20),
        ),
    ]
