# Generated by Django 4.2 on 2025-12-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_penyewaan_ongkir_penyewaan_ongkos_kirim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='bukti_bayar',
            field=models.ImageField(blank=True, null=True, upload_to='bukti_bayar/'),
        ),
    ]
