# Generated by Django 4.2 on 2026-01-06 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transaksi_bukti_bayar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penyewaan',
            name='paket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.paket'),
        ),
        migrations.AddIndex(
            model_name='notifikasi',
            index=models.Index(fields=['user'], name='core_notifi_user_id_6fc2f9_idx'),
        ),
        migrations.AddIndex(
            model_name='notifikasi',
            index=models.Index(fields=['sudah_dibaca'], name='core_notifi_sudah_d_e7d459_idx'),
        ),
        migrations.AddIndex(
            model_name='notifikasi',
            index=models.Index(fields=['tanggal_dibuat'], name='core_notifi_tanggal_9cbfb5_idx'),
        ),
        migrations.AddIndex(
            model_name='penyewaan',
            index=models.Index(fields=['tgl_pasang'], name='core_penyew_tgl_pas_acc905_idx'),
        ),
        migrations.AddIndex(
            model_name='penyewaan',
            index=models.Index(fields=['status'], name='core_penyew_status_5fb181_idx'),
        ),
        migrations.AddIndex(
            model_name='penyewaan',
            index=models.Index(fields=['pelanggan'], name='core_penyew_pelangg_9ef6cd_idx'),
        ),
        migrations.AddIndex(
            model_name='penyewaan',
            index=models.Index(fields=['tanggal_dibuat'], name='core_penyew_tanggal_39b64b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaksi',
            index=models.Index(fields=['status'], name='core_transa_status_cca6d2_idx'),
        ),
        migrations.AddIndex(
            model_name='transaksi',
            index=models.Index(fields=['tanggal_transaksi'], name='core_transa_tanggal_beb0d6_idx'),
        ),
        migrations.AddIndex(
            model_name='transaksi',
            index=models.Index(fields=['penyewaan'], name='core_transa_penyewa_5fcf84_idx'),
        ),
    ]
